"""Generate an inspectable CMOS hierarchy; no behavioral logic sources."""
from pathlib import Path
def generate():
    pins=' '.join([f'a{i}' for i in range(8)]+[f'b{i}' for i in range(8)]+
                  ['op0','op1','op2']+[f'y{i}' for i in range(8)]+['carry','overflow','zero','vdd','vss'])
    lines=['* Generated by scripts/generate_netlist.py', '.subckt alu8 '+pins]
    def x(name,pins,gate): lines.append('X'+name+' '+' '.join(pins)+' vdd vss '+gate)
    for i in range(8):
        a,b=f'a{i}',f'b{i}'
        x(f'bsub{i}',[b,'op0',f'bs{i}'],'xor2')
        x(f'fa{i}',[a,f'bs{i}','op0' if i==0 else f'c{i}',f's{i}',f'c{i+1}'],'fulladd')
        for gate,prefix in [('and2','and'),('or2','or'),('xor2','xor')]:
            x(f'{prefix}{i}',[a,b,f'{prefix}{i}'],gate)
        x(f'not{i}',[a,f'not{i}'],'inv')
        x(f'logic{i}',[f'and{i}',f'or{i}','op0',f'l{i}'],'mux2')
        x(f'unary{i}',[f'xor{i}',f'not{i}','op0',f'u{i}'],'mux2')
        x(f'shift{i}',['vss' if i==0 else f'a{i-1}', 'vss' if i==7 else f'a{i+1}', 'op0',f'h{i}'],'mux2')
        x(f'lo{i}',[f's{i}',f'l{i}','op1',f'lo{i}'],'mux2')
        x(f'hi{i}',[f'u{i}',f'h{i}','op1',f'hi{i}'],'mux2')
        x(f'out{i}',[f'lo{i}',f'hi{i}','op2',f'y{i}'],'mux2')
    x('arithlo',['op1','op2','arith'],'nor2')
    x('carryarith',['arith','c8','ca'],'and2')
    x('shiftcarry',['a7','a0','op0','cs'],'mux2')
    x('shiften',['op1','op2','sh'],'and2')
    x('carryshift',['sh','cs','ch'],'and2')
    x('carry',['ca','ch','carry'],'or2')
    x('overraw',['c7','c8','ov'],'xor2')
    x('overflow',['arith','ov','overflow'],'and2')
    accum='y0'
    for i in range(1,8):
        x(f'zero{i}',[accum,f'y{i}',f'z{i}'],'or2'); accum=f'z{i}'
    x('zero',[accum,'zero'],'inv')
    lines.append('.ends alu8')
    return '\n'.join(lines)+'\n'
if __name__=='__main__':
    (Path(__file__).resolve().parents[1]/'spice/alu8.cir').write_text(generate())
